/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DriverAuthRouteImport } from './routes/driver-auth'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedMyOrdersRouteImport } from './routes/_authenticated/my-orders'
import { Route as AuthenticatedMyCouponsRouteImport } from './routes/_authenticated/my-coupons'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedDashboardZonesRouteImport } from './routes/_authenticated/dashboard.zones'
import { Route as AuthenticatedDashboardThemeRouteImport } from './routes/_authenticated/dashboard.theme'
import { Route as AuthenticatedDashboardSupportRouteImport } from './routes/_authenticated/dashboard.support'
import { Route as AuthenticatedDashboardSettlementsRouteImport } from './routes/_authenticated/dashboard.settlements'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardReviewsRouteImport } from './routes/_authenticated/dashboard.reviews'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard.reports'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedDashboardMenuRouteImport } from './routes/_authenticated/dashboard.menu'
import { Route as AuthenticatedDashboardLoyaltyRouteImport } from './routes/_authenticated/dashboard.loyalty'
import { Route as AuthenticatedDashboardDriversHistoryRouteImport } from './routes/_authenticated/dashboard.drivers-history'
import { Route as AuthenticatedDashboardDriversRouteImport } from './routes/_authenticated/dashboard.drivers'
import { Route as AuthenticatedDashboardCouponsRouteImport } from './routes/_authenticated/dashboard.coupons'
import { Route as AuthenticatedDashboardBroadcastRouteImport } from './routes/_authenticated/dashboard.broadcast'
import { Route as AuthenticatedDashboardBranchesRouteImport } from './routes/_authenticated/dashboard.branches'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSearchRouteImport } from './routes/_authenticated/admin.search'
import { Route as AuthenticatedAdminChatMonitorRouteImport } from './routes/_authenticated/admin.chat-monitor'
import { Route as AuthenticatedAccountAddressesRouteImport } from './routes/_authenticated/account.addresses'
import { Route as AuthenticatedAdminTenantsIndexRouteImport } from './routes/_authenticated/admin.tenants.index'
import { Route as ApiPublicManifestSlugRouteImport } from './routes/api/public/manifest.$slug'
import { Route as ApiPublicIconSlugRouteImport } from './routes/api/public/icon.$slug'
import { Route as AuthenticatedDashboardBBranchSlugRouteImport } from './routes/_authenticated/dashboard.b.$branchSlug'
import { Route as AuthenticatedAdminTenantsIdRouteImport } from './routes/_authenticated/admin.tenants.$id'

const DriverAuthRoute = DriverAuthRouteImport.update({
  id: '/driver-auth',
  path: '/driver-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyOrdersRoute = AuthenticatedMyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyCouponsRoute = AuthenticatedMyCouponsRouteImport.update({
  id: '/my-coupons',
  path: '/my-coupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardZonesRoute =
  AuthenticatedDashboardZonesRouteImport.update({
    id: '/zones',
    path: '/zones',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardThemeRoute =
  AuthenticatedDashboardThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSupportRoute =
  AuthenticatedDashboardSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettlementsRoute =
  AuthenticatedDashboardSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReviewsRoute =
  AuthenticatedDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMenuRoute =
  AuthenticatedDashboardMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLoyaltyRoute =
  AuthenticatedDashboardLoyaltyRouteImport.update({
    id: '/loyalty',
    path: '/loyalty',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDriversHistoryRoute =
  AuthenticatedDashboardDriversHistoryRouteImport.update({
    id: '/drivers-history',
    path: '/drivers-history',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDriversRoute =
  AuthenticatedDashboardDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCouponsRoute =
  AuthenticatedDashboardCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBroadcastRoute =
  AuthenticatedDashboardBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBranchesRoute =
  AuthenticatedDashboardBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSearchRoute =
  AuthenticatedAdminSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChatMonitorRoute =
  AuthenticatedAdminChatMonitorRouteImport.update({
    id: '/chat-monitor',
    path: '/chat-monitor',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountAddressesRoute =
  AuthenticatedAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminTenantsIndexRoute =
  AuthenticatedAdminTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicManifestSlugRoute = ApiPublicManifestSlugRouteImport.update({
  id: '/api/public/manifest/$slug',
  path: '/api/public/manifest/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIconSlugRoute = ApiPublicIconSlugRouteImport.update({
  id: '/api/public/icon/$slug',
  path: '/api/public/icon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardBBranchSlugRoute =
  AuthenticatedDashboardBBranchSlugRouteImport.update({
    id: '/b/$branchSlug',
    path: '/b/$branchSlug',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminTenantsIdRoute =
  AuthenticatedAdminTenantsIdRouteImport.update({
    id: '/tenants/$id',
    path: '/tenants/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/driver-auth': typeof DriverAuthRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/driver': typeof AuthenticatedDriverRoute
  '/my-coupons': typeof AuthenticatedMyCouponsRoute
  '/my-orders': typeof AuthenticatedMyOrdersRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/r/$slug': typeof RSlugRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/admin/chat-monitor': typeof AuthenticatedAdminChatMonitorRoute
  '/admin/search': typeof AuthenticatedAdminSearchRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/branches': typeof AuthenticatedDashboardBranchesRoute
  '/dashboard/broadcast': typeof AuthenticatedDashboardBroadcastRoute
  '/dashboard/coupons': typeof AuthenticatedDashboardCouponsRoute
  '/dashboard/drivers': typeof AuthenticatedDashboardDriversRoute
  '/dashboard/drivers-history': typeof AuthenticatedDashboardDriversHistoryRoute
  '/dashboard/loyalty': typeof AuthenticatedDashboardLoyaltyRoute
  '/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/settlements': typeof AuthenticatedDashboardSettlementsRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/dashboard/theme': typeof AuthenticatedDashboardThemeRoute
  '/dashboard/zones': typeof AuthenticatedDashboardZonesRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/tenants/$id': typeof AuthenticatedAdminTenantsIdRoute
  '/dashboard/b/$branchSlug': typeof AuthenticatedDashboardBBranchSlugRoute
  '/api/public/icon/$slug': typeof ApiPublicIconSlugRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
  '/admin/tenants/': typeof AuthenticatedAdminTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/driver-auth': typeof DriverAuthRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/driver': typeof AuthenticatedDriverRoute
  '/my-coupons': typeof AuthenticatedMyCouponsRoute
  '/my-orders': typeof AuthenticatedMyOrdersRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/r/$slug': typeof RSlugRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/admin/chat-monitor': typeof AuthenticatedAdminChatMonitorRoute
  '/admin/search': typeof AuthenticatedAdminSearchRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/branches': typeof AuthenticatedDashboardBranchesRoute
  '/dashboard/broadcast': typeof AuthenticatedDashboardBroadcastRoute
  '/dashboard/coupons': typeof AuthenticatedDashboardCouponsRoute
  '/dashboard/drivers': typeof AuthenticatedDashboardDriversRoute
  '/dashboard/drivers-history': typeof AuthenticatedDashboardDriversHistoryRoute
  '/dashboard/loyalty': typeof AuthenticatedDashboardLoyaltyRoute
  '/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/settlements': typeof AuthenticatedDashboardSettlementsRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/dashboard/theme': typeof AuthenticatedDashboardThemeRoute
  '/dashboard/zones': typeof AuthenticatedDashboardZonesRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/tenants/$id': typeof AuthenticatedAdminTenantsIdRoute
  '/dashboard/b/$branchSlug': typeof AuthenticatedDashboardBBranchSlugRoute
  '/api/public/icon/$slug': typeof ApiPublicIconSlugRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/driver-auth': typeof DriverAuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/my-coupons': typeof AuthenticatedMyCouponsRoute
  '/_authenticated/my-orders': typeof AuthenticatedMyOrdersRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/r/$slug': typeof RSlugRoute
  '/_authenticated/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/_authenticated/admin/chat-monitor': typeof AuthenticatedAdminChatMonitorRoute
  '/_authenticated/admin/search': typeof AuthenticatedAdminSearchRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/dashboard/branches': typeof AuthenticatedDashboardBranchesRoute
  '/_authenticated/dashboard/broadcast': typeof AuthenticatedDashboardBroadcastRoute
  '/_authenticated/dashboard/coupons': typeof AuthenticatedDashboardCouponsRoute
  '/_authenticated/dashboard/drivers': typeof AuthenticatedDashboardDriversRoute
  '/_authenticated/dashboard/drivers-history': typeof AuthenticatedDashboardDriversHistoryRoute
  '/_authenticated/dashboard/loyalty': typeof AuthenticatedDashboardLoyaltyRoute
  '/_authenticated/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/settlements': typeof AuthenticatedDashboardSettlementsRoute
  '/_authenticated/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/_authenticated/dashboard/theme': typeof AuthenticatedDashboardThemeRoute
  '/_authenticated/dashboard/zones': typeof AuthenticatedDashboardZonesRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/admin/tenants/$id': typeof AuthenticatedAdminTenantsIdRoute
  '/_authenticated/dashboard/b/$branchSlug': typeof AuthenticatedDashboardBBranchSlugRoute
  '/api/public/icon/$slug': typeof ApiPublicIconSlugRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
  '/_authenticated/admin/tenants/': typeof AuthenticatedAdminTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/driver-auth'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/driver'
    | '/my-coupons'
    | '/my-orders'
    | '/wallet'
    | '/r/$slug'
    | '/account/addresses'
    | '/admin/chat-monitor'
    | '/admin/search'
    | '/admin/users'
    | '/dashboard/branches'
    | '/dashboard/broadcast'
    | '/dashboard/coupons'
    | '/dashboard/drivers'
    | '/dashboard/drivers-history'
    | '/dashboard/loyalty'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reports'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/settlements'
    | '/dashboard/support'
    | '/dashboard/theme'
    | '/dashboard/zones'
    | '/orders/$id'
    | '/admin/'
    | '/dashboard/'
    | '/admin/tenants/$id'
    | '/dashboard/b/$branchSlug'
    | '/api/public/icon/$slug'
    | '/api/public/manifest/$slug'
    | '/admin/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/driver-auth'
    | '/account'
    | '/driver'
    | '/my-coupons'
    | '/my-orders'
    | '/wallet'
    | '/r/$slug'
    | '/account/addresses'
    | '/admin/chat-monitor'
    | '/admin/search'
    | '/admin/users'
    | '/dashboard/branches'
    | '/dashboard/broadcast'
    | '/dashboard/coupons'
    | '/dashboard/drivers'
    | '/dashboard/drivers-history'
    | '/dashboard/loyalty'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reports'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/settlements'
    | '/dashboard/support'
    | '/dashboard/theme'
    | '/dashboard/zones'
    | '/orders/$id'
    | '/admin'
    | '/dashboard'
    | '/admin/tenants/$id'
    | '/dashboard/b/$branchSlug'
    | '/api/public/icon/$slug'
    | '/api/public/manifest/$slug'
    | '/admin/tenants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/driver-auth'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/driver'
    | '/_authenticated/my-coupons'
    | '/_authenticated/my-orders'
    | '/_authenticated/wallet'
    | '/r/$slug'
    | '/_authenticated/account/addresses'
    | '/_authenticated/admin/chat-monitor'
    | '/_authenticated/admin/search'
    | '/_authenticated/admin/users'
    | '/_authenticated/dashboard/branches'
    | '/_authenticated/dashboard/broadcast'
    | '/_authenticated/dashboard/coupons'
    | '/_authenticated/dashboard/drivers'
    | '/_authenticated/dashboard/drivers-history'
    | '/_authenticated/dashboard/loyalty'
    | '/_authenticated/dashboard/menu'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/reviews'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/settlements'
    | '/_authenticated/dashboard/support'
    | '/_authenticated/dashboard/theme'
    | '/_authenticated/dashboard/zones'
    | '/_authenticated/orders/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/admin/tenants/$id'
    | '/_authenticated/dashboard/b/$branchSlug'
    | '/api/public/icon/$slug'
    | '/api/public/manifest/$slug'
    | '/_authenticated/admin/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DriverAuthRoute: typeof DriverAuthRoute
  RSlugRoute: typeof RSlugRoute
  ApiPublicIconSlugRoute: typeof ApiPublicIconSlugRoute
  ApiPublicManifestSlugRoute: typeof ApiPublicManifestSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/driver-auth': {
      id: '/driver-auth'
      path: '/driver-auth'
      fullPath: '/driver-auth'
      preLoaderRoute: typeof DriverAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-orders': {
      id: '/_authenticated/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof AuthenticatedMyOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-coupons': {
      id: '/_authenticated/my-coupons'
      path: '/my-coupons'
      fullPath: '/my-coupons'
      preLoaderRoute: typeof AuthenticatedMyCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/zones': {
      id: '/_authenticated/dashboard/zones'
      path: '/zones'
      fullPath: '/dashboard/zones'
      preLoaderRoute: typeof AuthenticatedDashboardZonesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/theme': {
      id: '/_authenticated/dashboard/theme'
      path: '/theme'
      fullPath: '/dashboard/theme'
      preLoaderRoute: typeof AuthenticatedDashboardThemeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/support': {
      id: '/_authenticated/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof AuthenticatedDashboardSupportRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settlements': {
      id: '/_authenticated/dashboard/settlements'
      path: '/settlements'
      fullPath: '/dashboard/settlements'
      preLoaderRoute: typeof AuthenticatedDashboardSettlementsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reviews': {
      id: '/_authenticated/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof AuthenticatedDashboardReviewsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/menu': {
      id: '/_authenticated/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof AuthenticatedDashboardMenuRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/loyalty': {
      id: '/_authenticated/dashboard/loyalty'
      path: '/loyalty'
      fullPath: '/dashboard/loyalty'
      preLoaderRoute: typeof AuthenticatedDashboardLoyaltyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/drivers-history': {
      id: '/_authenticated/dashboard/drivers-history'
      path: '/drivers-history'
      fullPath: '/dashboard/drivers-history'
      preLoaderRoute: typeof AuthenticatedDashboardDriversHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/drivers': {
      id: '/_authenticated/dashboard/drivers'
      path: '/drivers'
      fullPath: '/dashboard/drivers'
      preLoaderRoute: typeof AuthenticatedDashboardDriversRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/coupons': {
      id: '/_authenticated/dashboard/coupons'
      path: '/coupons'
      fullPath: '/dashboard/coupons'
      preLoaderRoute: typeof AuthenticatedDashboardCouponsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/broadcast': {
      id: '/_authenticated/dashboard/broadcast'
      path: '/broadcast'
      fullPath: '/dashboard/broadcast'
      preLoaderRoute: typeof AuthenticatedDashboardBroadcastRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/branches': {
      id: '/_authenticated/dashboard/branches'
      path: '/branches'
      fullPath: '/dashboard/branches'
      preLoaderRoute: typeof AuthenticatedDashboardBranchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/search': {
      id: '/_authenticated/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AuthenticatedAdminSearchRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chat-monitor': {
      id: '/_authenticated/admin/chat-monitor'
      path: '/chat-monitor'
      fullPath: '/admin/chat-monitor'
      preLoaderRoute: typeof AuthenticatedAdminChatMonitorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/addresses': {
      id: '/_authenticated/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AuthenticatedAccountAddressesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/tenants/': {
      id: '/_authenticated/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AuthenticatedAdminTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/manifest/$slug': {
      id: '/api/public/manifest/$slug'
      path: '/api/public/manifest/$slug'
      fullPath: '/api/public/manifest/$slug'
      preLoaderRoute: typeof ApiPublicManifestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/icon/$slug': {
      id: '/api/public/icon/$slug'
      path: '/api/public/icon/$slug'
      fullPath: '/api/public/icon/$slug'
      preLoaderRoute: typeof ApiPublicIconSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/b/$branchSlug': {
      id: '/_authenticated/dashboard/b/$branchSlug'
      path: '/b/$branchSlug'
      fullPath: '/dashboard/b/$branchSlug'
      preLoaderRoute: typeof AuthenticatedDashboardBBranchSlugRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/tenants/$id': {
      id: '/_authenticated/admin/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AuthenticatedAdminTenantsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountAddressesRoute: typeof AuthenticatedAccountAddressesRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountAddressesRoute: AuthenticatedAccountAddressesRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminChatMonitorRoute: typeof AuthenticatedAdminChatMonitorRoute
  AuthenticatedAdminSearchRoute: typeof AuthenticatedAdminSearchRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminTenantsIdRoute: typeof AuthenticatedAdminTenantsIdRoute
  AuthenticatedAdminTenantsIndexRoute: typeof AuthenticatedAdminTenantsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminChatMonitorRoute: AuthenticatedAdminChatMonitorRoute,
  AuthenticatedAdminSearchRoute: AuthenticatedAdminSearchRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminTenantsIdRoute: AuthenticatedAdminTenantsIdRoute,
  AuthenticatedAdminTenantsIndexRoute: AuthenticatedAdminTenantsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBranchesRoute: typeof AuthenticatedDashboardBranchesRoute
  AuthenticatedDashboardBroadcastRoute: typeof AuthenticatedDashboardBroadcastRoute
  AuthenticatedDashboardCouponsRoute: typeof AuthenticatedDashboardCouponsRoute
  AuthenticatedDashboardDriversRoute: typeof AuthenticatedDashboardDriversRoute
  AuthenticatedDashboardDriversHistoryRoute: typeof AuthenticatedDashboardDriversHistoryRoute
  AuthenticatedDashboardLoyaltyRoute: typeof AuthenticatedDashboardLoyaltyRoute
  AuthenticatedDashboardMenuRoute: typeof AuthenticatedDashboardMenuRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardReviewsRoute: typeof AuthenticatedDashboardReviewsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSettlementsRoute: typeof AuthenticatedDashboardSettlementsRoute
  AuthenticatedDashboardSupportRoute: typeof AuthenticatedDashboardSupportRoute
  AuthenticatedDashboardThemeRoute: typeof AuthenticatedDashboardThemeRoute
  AuthenticatedDashboardZonesRoute: typeof AuthenticatedDashboardZonesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardBBranchSlugRoute: typeof AuthenticatedDashboardBBranchSlugRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBranchesRoute: AuthenticatedDashboardBranchesRoute,
    AuthenticatedDashboardBroadcastRoute: AuthenticatedDashboardBroadcastRoute,
    AuthenticatedDashboardCouponsRoute: AuthenticatedDashboardCouponsRoute,
    AuthenticatedDashboardDriversRoute: AuthenticatedDashboardDriversRoute,
    AuthenticatedDashboardDriversHistoryRoute:
      AuthenticatedDashboardDriversHistoryRoute,
    AuthenticatedDashboardLoyaltyRoute: AuthenticatedDashboardLoyaltyRoute,
    AuthenticatedDashboardMenuRoute: AuthenticatedDashboardMenuRoute,
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardReviewsRoute: AuthenticatedDashboardReviewsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSettlementsRoute:
      AuthenticatedDashboardSettlementsRoute,
    AuthenticatedDashboardSupportRoute: AuthenticatedDashboardSupportRoute,
    AuthenticatedDashboardThemeRoute: AuthenticatedDashboardThemeRoute,
    AuthenticatedDashboardZonesRoute: AuthenticatedDashboardZonesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardBBranchSlugRoute:
      AuthenticatedDashboardBBranchSlugRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedMyCouponsRoute: typeof AuthenticatedMyCouponsRoute
  AuthenticatedMyOrdersRoute: typeof AuthenticatedMyOrdersRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedMyCouponsRoute: AuthenticatedMyCouponsRoute,
  AuthenticatedMyOrdersRoute: AuthenticatedMyOrdersRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DriverAuthRoute: DriverAuthRoute,
  RSlugRoute: RSlugRoute,
  ApiPublicIconSlugRoute: ApiPublicIconSlugRoute,
  ApiPublicManifestSlugRoute: ApiPublicManifestSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
